set dotenv-load := true

@start-api-dev:
    docker compose -f docker-compose-dev.yaml up --build

@stop-api-dev:
    # Remove Previous versions of this image.
    # They show up as <none>:<none> when a new image is created.
    docker image prune -f
    docker compose -f docker-compose-dev.yaml down

@pytest thingy="":
    docker compose -f docker-compose-test.yaml up -d --build
    # sleep needed because docker compose up doesn't care
    # what point start.sh gets to when it decides the containers are built
    # (we want the database migrations to finish)
    sleep 2
    -docker compose -f docker-compose-test.yaml exec fastapi_server_test python3 -m pytest {{thingy}}
    docker image prune -f
    docker compose -f docker-compose-test.yaml down

@down-test-services:
    # useful when pytest recipe fails before tearing down
    docker image prune -f
    docker compose -f docker-compose-test.yaml down
