"""create course enrollment table.

Revision ID: 3cf94c13dc50
Revises: 8d2ae9bf24fd
Create Date: 2024-03-31 17:50:00.148869

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cf94c13dc50"
down_revision: str | None = "8d2ae9bf24fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade version."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_enrollments",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "admin", "owner", name="enrollmenttype"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade version."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_enrollments")
    # ### end Alembic commands ###
