apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonfaas-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonfaas-controller
  template:
    metadata:
      labels:
        app: demonfaas-controller
    spec:
      containers:
      - name: controller
        image: jayanaka98/demonfaas-controller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080