version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    image: backend-fastapi_server:latest
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file: ".env"
    environment:
      - DATABASE_HOST=postgres_db
      - MEILI_HTTP_ADDR=meili:7700
    depends_on:
      - database

  database:
    container_name: postgres_db
    image: postgres:alpine
    # No Ports because API should connect over the docker network on 5432
    # Ports ONLY to access database to create alembic revisions
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  meilisearch:
    container_name: meili
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=true
