# Following documentation for release-drafter
# https://github.com/marketplace/actions/release-drafter

name: "Release Drafter"

on:
  push:
    branches:
      - main

jobs:
  update_release_drafter:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-draft-template.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
