apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonfaas-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonfaas-controller
  template:
    metadata:
      labels:
        app: demonfaas-controller
    spec:
      containers:
      - name: demonfaas-controller
        image: stoneann5490/demonfaas-controller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demonfaas-controller-service
spec:
  selector:
    app: demonfaas-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
