apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-04T20:23:50Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "1109"
  uid: e57436f5-39db-4e64-802b-a22714c9a7ef
