apiVersion: v1
data:
  insert.sql: |
    -- Generating 100,000 unique names using 'Name_' prefix followed by row number
    WITH RECURSIVE number_gen AS (
        SELECT 1 AS num
        UNION ALL
        SELECT num + 1
        FROM number_gen
        WHERE num < 100000
    )
    INSERT INTO read_heavy (read_name)
    SELECT CONCAT('Name_', num) AS read_name
    FROM number_gen;
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-19T20:58:46Z"
  name: postgres-insert-sql
  namespace: default
  resourceVersion: "1039"
  uid: a0e284cf-99a9-4324-ac90-36d49c3050ef
