apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-18T06:31:28Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "993"
  uid: 9a329a16-1ce2-49d0-90cd-ea1ac2442636
