apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-19T22:21:43Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "1022"
  uid: 3a761353-0961-4b77-bb4a-5aa4ac315358
