apiVersion: v1
data:
  insert.sql: |
    -- Generating 100,000 unique names using 'Name_' prefix followed by row number
    WITH RECURSIVE number_gen AS (
        SELECT 1 AS num
        UNION ALL
        SELECT num + 1
        FROM number_gen
        WHERE num < 100000
    )
    INSERT INTO read_heavy (read_name)
    SELECT CONCAT('Name_', num) AS read_name
    FROM number_gen;
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-04T20:23:50Z"
  name: postgres-insert-sql
  namespace: default
  resourceVersion: "1110"
  uid: e2435b2d-3b8b-431c-9e52-48ed47fa7180
