apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-22T18:15:02Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "1263"
  uid: f24e33b0-b1e6-4baf-9a8b-991d39c342a7
