apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-19T20:58:46Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "1037"
  uid: 2561b0cf-f39e-475e-b6a1-07120cb50c11
