name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_NAME: postgres

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Tests
        run: |
          docker compose -f docker-compose-test.yaml up -d --build
          sleep 5
          docker compose -f docker-compose-test.yaml exec fastapi_server_test python3 -m pytest
          docker compose -f docker-compose-test.yaml down
