apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-05T19:29:58Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "1052"
  uid: 5c28a575-be42-44e1-9bb7-1ae8125be4d2
