apiVersion: v1
data:
  insert.sql: |
    -- Generating 100,000 unique names using 'Name_' prefix followed by row number
    WITH RECURSIVE number_gen AS (
        SELECT 1 AS num
        UNION ALL
        SELECT num + 1
        FROM number_gen
        WHERE num < 100000
    )
    INSERT INTO read_heavy (read_name)
    SELECT CONCAT('Name_', num) AS read_name
    FROM number_gen;
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-05T14:18:57Z"
  name: postgres-insert-sql
  namespace: default
  resourceVersion: "1169"
  uid: d2b93fcc-cd50-42f2-af81-afab9e0eb3c6
