apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS read_heavy
    (
        read_name varchar(50) not null
    );

    CREATE TABLE IF NOT EXISTS write_heavy
    (
        write_id   int not null,
        write_name varchar(50) not null
    );
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-12T08:13:09Z"
  name: postgres-init-sql
  namespace: default
  resourceVersion: "488"
  uid: d8b3a835-46e5-4bd5-9965-c6deafc0b322
