# Creates a new resource
# like creating a object of a class in C++
apiVersion: myapi.example.com/v1
kind: ApiTransformation
metadata:
  name: demonfaas-transformation
spec:
  sourceApi: "http://localhost:9000"
  serverlessApi: "http://gateway.openfaas.svc.cluster.local:8080/function/benchmark-app"
  serverfulApi: "http://benchmark-app-service.default.svc.cluster.local:8000"
  requestThreshold: 100
  latencyThreshold: 0.5
  evaluationInterval: 30
  cooldownPeriod: 300