apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apitransformations-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: apitransformation-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: apitransformations-cluster-role
  apiGroup: rbac.authorization.k8s.io
