"""create question table.

Revision ID: 060e7bd0b679
Revises: 3cf94c13dc50
Create Date: 2024-04-01 19:22:33.880606

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "060e7bd0b679"
down_revision: str | None = "3cf94c13dc50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade version."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("is_starred_for_course", sa.Boolean(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id", "course_id"],
            ["course_enrollments.user_id", "course_enrollments.course_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade version."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
